name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
      - name: Copy files to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: 128.199.164.212
          username: root
          password: 4PTB!TZ9&cdhAT  # Use a GitHub secret for security
          script: |
            # Create the 'support-microservice' folder if it doesn't exist
            mkdir -p /support-microservice
            # Copy files from 'build' to 'support-microservice' folder
            cp -r build/* /support-microservice

      - name: Install PM2
        run: npm install -g pm2

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: 128.199.164.212
          username: root
          password: 4PTB!TZ9&cdhAT  # Use a GitHub secret for security
          script: |
            cd /support-microservice
            pm2 stop server || true
            pm2 delete server || true
            pm2 start main.js --name server
