name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Install PM2
        run: npm install -g pm2

      - name: Build
        run: npm run build

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: 128.199.164.212
          username: root
          # You should use SSH key-based authentication instead of password.
          # Generate an SSH key pair if you haven't already, and add the public key to the Droplet.
          # Then, store the private key as a secret in your GitHub repository and use it here.
          # Example: {{ secrets.SSH_PRIVATE_KEY }}
          password: 4PTB!TZ9&cdhAT
          script: |
            cd /
            npm ci
            npm run build
            pm2 stop support-microservice # Stop the previous instance if running.
            pm2 delete support-microservice # Delete the previous instance if exists.
            pm2 start dist/main.js --name support-microservice
