name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14


      - name: Install dependencies
        run: npm install


      - name: Install PM2
        run: npm install -g pm2


      - name: Build
        run: npm run build


      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: 128.199.164.212
          username: root
          password: ${{ secrets.pass }}
          script: |
            # Create a temporary directory for the build files
            mkdir -p /tmp/support-microservice
            
            # Copy the build files to the server's temporary directory
            cp -r dist /tmp/support-microservice
            cp package.json package-lock.json /tmp/support-microservice
            
            # Navigate to the application directory
            cd /root/support-microservice
            
            # Stop and delete the previous PM2 process if it exists
            pm2 stop support-microservice
            pm2 delete support-microservice
            
            # Copy the build files from the temporary directory to the application directory
            cp -r /tmp/support-microservice/* .
            
            # Install dependencies and start the application with PM2
            npm ci
            pm2 start main.js --name support-microservice
            
            # Cleanup: Remove the temporary directory
            rm -rf /tmp/support-microservice
